import { Hospital } from '../types';

export const HOSPITALS: Hospital[] = [
  {
    id: '1',
    name_en: 'Tribhuvan University Teaching Hospital',
    name_ne: 'त्रिभुवन विश्वविद्यालय शिक्षण अस्पताल',
    phone: '01-4412303',
    speciality: 'General / Trauma',
    speciality_ne: 'सामान्य / ट्रमा',
    lat: 27.7321,
    lng: 85.3319,
    address_en: 'Maharajgunj, Kathmandu',
    address_ne: 'महाराजगञ्ज, काठमाडौं',
  },
  {
    id: '2',
    name_en: 'Bir Hospital',
    name_ne: 'वीर अस्पताल',
    phone: '01-4221119',
    speciality: 'General / Emergency',
    speciality_ne: 'सामान्य / आपतकालीन',
    lat: 27.7041,
    lng: 85.3131,
    address_en: 'Kanti Path, Kathmandu',
    address_ne: 'कान्ति पथ, काठमाडौं',
  },
  {
    id: '3',
    name_en: 'Patan Hospital',
    name_ne: 'पाटन अस्पताल',
    phone: '01-5522278',
    speciality: 'General / Pediatric',
    speciality_ne: 'सामान्य / बाल',
    lat: 27.6723,
    lng: 85.3194,
    address_en: 'Lagankhel, Lalitpur',
    address_ne: 'लगनखेल, ललितपुर',
  },
  {
    id: '4',
    name_en: 'Grande International Hospital',
    name_ne: 'ग्रान्डे इन्टरनेशनल अस्पताल',
    phone: '01-5159266',
    speciality: 'Multi-specialty',
    speciality_ne: 'बहु-विशेषज्ञता',
    lat: 27.7361,
    lng: 85.3469,
    address_en: 'Tokha Chowk, Kathmandu',
    address_ne: 'टोखा चोक, काठमाडौं',
  },
  {
    id: '5',
    name_en: 'Norvic International Hospital',
    name_ne: 'नोर्भिक इन्टरनेशनल अस्पताल',
    phone: '01-4258554',
    speciality: 'Cardiac / Multi-specialty',
    speciality_ne: 'हृदय / बहु-विशेषज्ञता',
    lat: 27.7058,
    lng: 85.3202,
    address_en: 'Thapathali, Kathmandu',
    address_ne: 'थापाथली, काठमाडौं',
  },
  {
    id: '6',
    name_en: 'Nepal Medical College',
    name_ne: 'नेपाल मेडिकल कलेज',
    phone: '01-4911008',
    speciality: 'General',
    speciality_ne: 'सामान्य',
    lat: 27.7450,
    lng: 85.3730,
    address_en: 'Jorpati, Kathmandu',
    address_ne: 'जोरपाटी, काठमाडौं',
  },
  {
    id: '7',
    name_en: 'Kanti Children\'s Hospital',
    name_ne: 'कान्ति बाल अस्पताल',
    phone: '01-4412798',
    speciality: 'Pediatric',
    speciality_ne: 'बाल',
    lat: 27.7378,
    lng: 85.3207,
    address_en: 'Maharajgunj, Kathmandu',
    address_ne: 'महाराजगञ्ज, काठमाडौं',
  },
  {
    id: '8',
    name_en: 'Shahid Gangalal Heart Centre',
    name_ne: 'शहीद गंगालाल हृदय केन्द्र',
    phone: '01-4371322',
    speciality: 'Cardiac',
    speciality_ne: 'हृदय',
    lat: 27.7365,
    lng: 85.3226,
    address_en: 'Bansbari, Kathmandu',
    address_ne: 'बाँसबारी, काठमाडौं',
  },
  {
    id: '9',
    name_en: 'National Trauma Centre',
    name_ne: 'राष्ट्रिय ट्रमा केन्द्र',
    phone: '01-4412505',
    speciality: 'Trauma',
    speciality_ne: 'ट्रमा',
    lat: 27.7350,
    lng: 85.3310,
    address_en: 'Maharajgunj, Kathmandu',
    address_ne: 'महाराजगञ्ज, काठमाडौं',
  },
];
